### ISSUE TITLE
name 'LAU' is not defined for lens import

### ISSUE THREAD

**Issue by subatomike** [mjhoptics/ray-optics#160]
I'm importing Edmund lens [16-998](https://www.edmundoptics.com/p/25mm-dia-033-numerical-aperture-900-1700nm-coated-high-precision-aspheric-lens/46190/) and get the error in the title. Upon inspection of the CodeV .seq file, you can see in the .seq below, which seems to be a layer of Norland epoxy, based on the NOA62 text. How can I deal with this error?

`RDM;LEN       "VERSION: 11.1 SR1       LENS VERSION: 83       Creation Date: 03-Feb-2023"
TITLE 'codv_16998'
EPD   25.0
DIM   M
WL    587.6
REF   1
WTW   1
INI   'EO '
XAN   0.0
YAN   0.0
WTF   5.0
VUY   0.0
VLY   0.0
PRV  
  PWL 550.0
  'NOA61' LAU 2.36390625 0.0 0.025493134 -0.000580235 -0.349933e-5 0.445404e-7
END  
SO    0.0 0.1e14
S     19.38 9.720976918833829 NBK7_SCHOTT
  STO
  ASP
  K   -0.6698934
  CUF 0.0
  A   0.1876737e-5; B 0.8930244e-9; C 0.0; D 0.0
  CIR 12.5
S     0.0 31.09123483490374
  CIR 12.5
  PIM
SI    0.0 0.0
GO `

**Comment by mjhoptics** [comment]
Hello @subatomike,
I've looked at this and it turns out that the lens definition doesn't need the epoxy material. So you can just remove the following lines and the model should import successfully.

REMOVE:
```
PRV  
  PWL 550.0
  'NOA61' LAU 2.36390625 0.0 0.025493134 -0.000580235 -0.349933e-5 0.445404e-7
END  
```

If the model had required this definition, work would need to be done to define the material. Here are 2 possibilities:

- Use the [RefractiveIndex.Info](https://refractiveindex.info) website to get the material data. [Norland 61](https://refractiveindex.info/?shelf=other&book=Norland_NOA-61&page=Norland) is in the database. You could create a material like this:
```
NOA_61_url = 'https://refractiveindex.info/database/data-nk/other/optical%20adhesives/NOA-61/Norland.yml'
NOA_61 = create_glass(NOA_61_url, "rindexinfo")
sm.gaps[1].medium = NOA_61
```

- write a short python script to evaluate the Laurent approximation used in the CODE V .seq file. Take the resulting wavelength/index pairs and create an instance of [InterpolatedMedium](https://opticalglass.readthedocs.io/en/stable/opticalglass.html#opticalglass.opticalmedium.InterpolatedMedium). 

Hope this helps.
Mike Hayford

**Comment by subatomike** [comment]
Makes sense. Thank you.
