### ISSUE TITLE
Software crash on linux after initialization with rayoptics

### ISSUE THREAD

**Issue by mv4manishverma** [mjhoptics/ray-optics#6]
The problem is in the name of OpticalGlass/Data/SUMITA.xlsx file. The software wants to read it as 'Sumita.xlsx' after initialization. Although, It works after you change the name as above but it's better to update the code to read it in it's standard form.

**Comment by mjhoptics** [comment]
It looks like this was fixed in the opticalglass repo in this update:
0dbb83aa95eef33c02d521146614dcfd16555958
It should be in the v0.4.5 release of opticalglass. ray-optics depends on opticalglass for all of the glass catalog support.
If you update your opticalglass and the problem goes away, the issue can be closed. Thanks!
