### ISSUE TITLE
plt.figure does not open graphics window

### ISSUE THREAD

**Issue by jhaupt** [mjhoptics/ray-optics#8]
First, MANY KUDOS for writing a FOSS optical design solution. It's been a long time coming and it's especially nice to have a solution for Linux. I've long been tempted to do write my own (having especially strong ideas of what a GUI might be like), but one has only so many hours in the day. I see you used to work on SYNOPSYS. It's funny, I just found this ray-optics project after the free trial they sent me wouldn't run on a virtual machine (it detected it was in a virtual machine and quit), and I got it to run in WINE exactly once. Anyway, left a bad taste in my mouth before even trying it. Have experience with Zemax and OSLO, and I'm ready for something different. Anyway, thank you! THANK YOU.

I've tried this on two different PCs, both running Debian 10. Going through the Triplet Example tutorial, when I run `layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, do_draw_rays=True, do_paraxial_layout=False, is_dark=isdark).plot()`, nothing happens, though I expect that this is what should open the graphics window showing the raytrace. I wondered if there's a step missing in the docs, i.e. something like plt.show(layout_plt)?

If I run just `plt.figure(FigureClass=InteractiveLayout, opt_model=opm, do_draw_rays=True, do_paraxial_layout=False, is_dark=isdark).plot()`, it spits out <InteractiveLayout size 640x480 with 1 Axes>, so it seems like things are otherwise functioning.

On a *possibly* related note, I can't find the mysterious desktop application. The command "rayoptics" isn't in my path, and I haven't figured out where the binary might be.

~Justine

**Comment by mjhoptics** [comment]
Thanks for the kind comments. 

I've found that subtle changes in how you write an expression can lead to no figures, 1 figure or more than one! Please try the following in a notebook cell:
layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, do_draw_rays=True, do_paraxial_layout=False, is_dark=isdark)
layout_plt.plot()

This should produce a plot. If it doesn't we'll probably have to drill deeper into versions, etc.

The rayoptics command is some magic script to run the main program in the qtgui module. If you cd to the rayoptics root directory in the python package directories and then run:
python qtgui/rayopticsapp.py
that should have the same effect as the rayoptics command does. It's some sort of setup.cfg magic the installer is supposed to handle.

**Comment by jhaupt** [comment]
Believe it or not I'd never tried Jupyter or such (I always work in native Python), but just tried it and it worked great. Maybe I'll have to get used to it. Thanks!

**Comment by jhaupt** [comment]
Holy Mother of Ray Propagation!

I just got the GUI program to run and it's beautiful! Apologies for the exclamation point abuse, but I really didn't expect to find this. I think you're really doing yourself a disservice by not putting up a dedicated website with some screenshots of what you've accomplished. I assumed, given the docs, that this was purely a scripting program and the GUI _might_ provide some interesting extra features, but gosh darnit, the GUI is the centerpiece. Why not at least show it off in the docs?

**Comment by mjhoptics** [comment]
Hi Justine,
Glad you're going again. GUI programs are very time consuming to document, so I've been putting it off. I'll try to create a video or two to highlight this. The GUI version seems more responsive to me than using Jupyter Lab or Notebook, but there are a lot of things you can do via scripting that haven't been implemented in the GUI.
Thanks for your encouragement.

**Comment by diplodocuslongus** [comment]
I fully second Justine's enthusiasm about this work, thank you @mjhoptics and what a great work.

A small comment on this issue: trying to run a standalone script rather than using the GUI or jupyter notebook, I've encountered the same as Justine (I'm also on Linux but I don't think it's OS dependent).
I confirm that to display a ray diagram when running a standalone script (or from an interactive python session), `.show()` is required:
```
layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, do_draw_rays=True, do_paraxial_layout=False, is_dark=False)
layout_plt.show()
```
`layout_plt.plot()` will not show anything.

Note that for some reason, simply using `layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, is_dark=False)` (without `do_draw_rays=True, do_paraxial_layout=False`) results in a correct but very small ray diagram at the bottom left corner of the matplotlib figure.

Ludovic

**Comment by mjhoptics** [comment]
Hello Ludovic,

I confess that Matplotlib's behavior in different environments baffles me sometimes. If you could, would you execute this command in your environment:
`mpl.get_backend()`
If I can run using the same backend as yours, I can at least try to reproduce your problem.

I have issues in Jupyter notebooks with plots coming out very small. A way I've found to control the size is the dpi parameter when creating the figure. For the aberration plots, `dpi=150` or `dpi=200` work well in my notebooks. If you can try this and see what happens in your environment, that would be a useful data point.

Thank you for your kind comments.

Mike

**Comment by diplodocuslongus** [comment]
Mike, I hadn't thought about the backend of mpl as a potential cause of these quirks!
Mine is `Qt5Agg`.

Actually my comment was more to suggest a fix to plots not showing when running standalone ray-optics scripts (I mean `.py` programs) rather than to report a problem. 

But well... indeed, matplotlib behavior is baffling!

> I have issues in Jupyter notebooks with plots coming out very small. 

If they are small and in a corner of the figure I encountered this as well while experimenting as a follow-up to your reply (see below), otherwise my plots have all been of normal sizes.

In my jupyter notebook, `mpl_get_backend()` shows: `module://ipympl.backend_nbagg`. 

If I run the notebook with `%matplotlib widget` at the top:

- With `layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, is_dark=isdark)` (no added `.plot()`) I see a tiny layout diagram in the bottom left corner of the image in the cell, the image has control buttons for interacting (but no button would bring the diagram to a normal size).
- If in the next cell I do `layout_plt.plot()`, a plot is produced in the cell and, surprise, the cell above (which had the tiny diagram in the bottom left corner) gets updates to a normal sized diagram!
- With `layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, is_dark=isdark).plot()` the plot is of a normal size.

With the magic `%matplotlib inline`:
- `layout_plt = plt.figure(FigureClass=InteractiveLayout, opt_model=opm, is_dark=isdark)` produces `<InteractiveLayout size 432x288 with 0 Axes>` and no plot; adding `layout_plt.plot()` in the next cell will display the diagram.

For the aberration plots (tested only with `%matplotlib widget` ):
```
abr_plt = plt.figure(FigureClass=RayFanFigure, opt_model=opm, data_type='Ray', scale_type=Fit.All_Same, is_dark=False)
abr_plt.plot()
```
in the same cell, produces 2 plots on top of each other in that cell (one with and one without the control buttons)!
- With `abr_plt = plt.figure(FigureClass=RayFanFigure, opt_model=opm, data_type='Ray', scale_type=Fit.All_Same, is_dark=False)` in one cell, an empty figure is shown, and with `abr_plt.plot()` in the following cell, an interactive ray diagram is show and the above cell (which had the empty figure) is updated.

- ```abr_plt = plt.figure(FigureClass=RayFanFigure, opt_model=opm, data_type='Ray', scale_type=Fit.All_Same, is_dark=False).plot()``` produces a normal sized and single figure.

All my ray fan figures plots are shown with a normal size.

For spot diagrams, using
```
spot_plt = plt.figure(FigureClass=SpotDiagramFigure, opt_model=opm,
                      scale_type=Fit.User_Scale,
                      user_scale_value=0.05,
                      is_dark=isdark).plot()
```
 
as in your Chrétien-Ritchey [example](https://github.com/mjhoptics/ray-optics/issues/16#issuecomment-748286522) shows rather small plots indeed, but this approach (slightly modified from the example above to match your new API): 
```
spotfig.subplots = []
for f in range(num_flds):
    spotfig.subplots += [RayGeoPSF(ray_lists[f],
                                   user_scale_value=us,
                                   scale_type='user',dsp_typ='spot',
                                   yaxis_ticks_position='left', 
                                   title="Field {:d}".format(f),
                                   cmap='gray')]
```

produces good looking diagrams.

Ludo

**Comment by mjhoptics** [comment]
Well, I've poked around a bit and this may be more of a pyplot "feature". Looking at the doc for [show()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html#matplotlib.pyplot.show) reveals that 

> jupyter backends (activated via %matplotlib inline, %matplotlib notebook, or %matplotlib widget), call show() at the end of every cell by default.

That probably means there's a notebook setting somewhere that will turn off the auto-show behavior. 

There is also mention of `interactive mode` which has some interesting side effects including "figures will automatically redraw on change". I think this is what we see with previous cells redrawing when a plot() command is executed on a plot instance.

Your report of plotting behave in the notebook environment (sometimes 2 plots, sometimes no plot but an object id, etc.) match the experience I've had. I usually use `inline` when trying to produce a clean version of the notebook for doc use and `widget` when I want to work interactively, e.g. with a plot and ipywidgets. Maybe pyplot is adding a layer that I'm fighting with in these situations.

Cheers

Mike
